// Generated by https://quicktype.io

export interface FetchAllPokemonResponse {
    count:    number;
    next:     null;
    previous: null;
    results:  Result[];
}

export interface Result {
    name: string;
    url:  string;
}

export interface Pokemon {
    id: string;
    name: string;
    pic: string;
}